source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.3'
gem 'rouge', '~> 4.2'
gem 'jekyll-paginate', '~> 1.1'
gem 'wdm',              '>= 0.1.0'
gem 'jekyll-paginate'
gem 'csv'
gem 'base64'
gem 'bigdecimal'
gem 'rexml'
